name: deploy to lambda
# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
env:
  AWS_REGION: 'eu-west-2'

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest  
    steps:
      - name: Git clone the repository
        uses: actions/checkout@master
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::407026129471:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Deploy code to Lambda
        uses: mariamrf/py-lambda-action@v1.0.0
        with:
          lambda_layer_arn: 'arn:aws:lambda:eu-west-2:407026129471:function:my-github-test'
          lambda_function_name: 'my-github-test'
